import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Container } from 'react-bootstrap';
import Contactme from '../components/ContactMe';

export default function Contact() {
  return (
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>Contact Me</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='text-center pb-4'></div>
      <Container className='pt-5'>
        <Contactme />
      </Container>
      <Footer />
    </main>
  );
}