import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import AboutMe from '../components/AboutMe';
import { Container, Button, Card } from 'react-bootstrap';

export default function Home() {
  return (
    <>
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>About Me</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Container >
        <AboutMe />
      </Container>
      <Footer />
    </main>
    </>
  );
}